version: "3.8"
name: docs
services:
  site:
    build:
      context: .
      dockerfile: site.dockerfile
    image: site:latest
    ports:
      - "8081:80"
    environment:
      NGINX_PORT: 80
    volumes:
      - "site:/usr/share/nginx/html/"
  publisher:
    build:
      context: .
      dockerfile: publisher.dockerfile
    image: publisher:latest
    volumes:
      - "drops:/docfxhelper/drops"
      - "workspace:/docfxhelper/workspace"
      - "site:/docfxhelper/site"
volumes:
  drops: 
    driver: local
    driver_opts:
      type: none
      o: bind
      device: d:\rnd\docker\docfxHelper\virtualVolume\drops
  workspace: 
    driver: local
    driver_opts:
      type: none
      o: bind
      device: d:\rnd\docker\docfxHelper\virtualVolume\workspace
  site:  
    driver: local
    driver_opts:
      type: none
      o: bind
      device: d:\rnd\docker\docfxHelper\virtualVolume\site\

