# docker compose --file docker.compose.yml --project-name docfxhelper build
# docker compose --file docker.compose.yml --project-name docfxhelper up
# docker compose --file docker.compose.yml --project-name docfxhelper down
# docker compose --file docker.compose.yml --project-name docfxhelper rm
name: docs
services:
  site:
    build:
      context: .
      dockerfile: site.dockerfile
    image: site:local
    ports:
      - "8084:80"
    environment:
      NGINX_PORT: 80
    volumes:
      - site:/usr/share/nginx/html/
  publisher:
    build:
      context: .
      dockerfile: publisher.dockerfile
    image: publisher:local
    volumes:
      - drops:/docfxhelper/drops
      - workspace:/docfxhelper/workspace
      - site:/docfxhelper/site
volumes:
  drops:
    external: true
    name: drops
  workspace:
    external: true
    name: workspace
  site:
    external: true
    name: site
