version: "3.8"
name: docs
services:
  site:
    build:
      context: .
      dockerfile: site.dockerfile
    image: site:latest
    ports:
      - "8081:80"
    environment:
      NGINX_PORT: 80
    volumes:
      - "docfxhelper_site:/usr/share/nginx/html/"
  publisher:
    build:
      context: .
      dockerfile: publisher.dockerfile
    image: publisher:latest
    volumes:
      - "docfxhelper_drops:/docfxhelper/drops"
      - "docfxhelper_workspace:/docfxhelper/workspace"
      - "docfxhelper_site:/docfxhelper/site"
volumes:
  docfxhelper_drops:
  docfxhelper_workspace: 
  docfxhelper_site:  
