apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\patwa\AppData\Local\Microsoft\WinGet\Links\kompose.exe --file .\docker.compose.yml convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: site
  name: site
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 80
  selector:
    io.kompose.service: site
status:
  loadBalancer: {}
