apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\patwa\AppData\Local\Microsoft\WinGet\Links\kompose.exe --file .\docker.compose.yml convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: site
  name: site
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: site
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\patwa\AppData\Local\Microsoft\WinGet\Links\kompose.exe --file .\docker.compose.yml convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/docs-default: "true"
        io.kompose.service: site
    spec:
      containers:
        - env:
            - name: NGINX_PORT
              value: "80"
          image: site:latest
          name: site
          ports:
            - containerPort: 80
              hostPort: 8081
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: docfxhelper-site
      restartPolicy: Always
      volumes:
        - name: docfxhelper-site
          persistentVolumeClaim:
            claimName: docfxhelper-site
status: {}
